name: jupyter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 11 * * *'  # run every day

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pip
      run: |
        python -m pip install --upgrade pip

    - name: Install TensorFlow ecosystem
      run: |
        pip install tensorflow
        pip install tensorflow_data_validation
        pip install tensorflow_hub
        pip install tensorflow-model-analysis

    - name: Install test dependencies
      run: |
        pip install nbformat
        pip install nbconvert

    - name: Set up Jupyter
      run: |
        pip install jupyter
        jupyter nbextension enable --py widgetsnbextension --sys-prefix
        jupyter nbextension install --py --symlink tensorflow_model_analysis --sys-prefix
        jupyter nbextension enable --py tensorflow_model_analysis --sys-prefix

    - name: Test Jupyter Notebooks
      run: python jupyter_test.py
